version: '3.1'
services:
  app:
    container_name: currency_rate_app
    image: currency-rate-service
    build: ./
    ports:
      - "9090:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employeedb